### PR TITLE
determine hostid using ascii chars

### PR DESCRIPTION
**Pull request by edoapra**
This commit avoids using the non standard hostid() call and the Cray specific PMI_gethostid.
It simply uses ascii characters from hostname to generate a long integer.
I have tested it using NWChem and ExaChem on Cray systems.

### CODE REVIEW

**Comment by bjpalmer** [comment]
Since the names can be up to 255 characters and there doesn't seem to be any formal standard on what format they take and where the unique identifying characters are located, maybe it would be better if we ditched an integer host ID altogether and just stored the names as the host identifier. This would require replacing all the long int hostid comparisons with strcmps. This should be straightforward, although tedious.

**Comment by edoapra** [comment]
> Since the names can be up to 255 characters and there doesn't seem to be any formal standard on what format they take and where the unique identifying characters are located, maybe it would be better if we ditched an integer host ID altogether and just stored the names as the host identifier. This would require replacing all the long int hostid comparisons with strcmps. This should be straightforward, although tedious.

I agree. This code can only handle up to 12 characters.

**Comment by bjpalmer** [comment]
@edoapra, I just created a new branch, feature/unique_names, that uses host names instead of host IDs.  See if that works for you.

**Comment by edoapra** [comment]
> @edoapra, I just created a new branch, feature/unique_names, that uses host names instead of host IDs. See if that works for you.

First test on frontier looks good

**Comment by edoapra** [comment]
> What is the consensus on this? Should we call it good and merge it into develop?

Yes, I would merge it

**Pull request closed without merging**
