### PR TITLE
fix for missing definition of ga_deallocate 

### PR DESCRIPTION
**Pull request by edoapra**
See issues  
https://github.com/nwchemgit/nwchem/issues/489    
https://github.com/GlobalArrays/ga/issues/238  
https://github.com/GlobalArrays/ga/issues/239

### CODE REVIEW

**Comment by yurivict** [comment]
Can a new release be made that includes this patch?
5.8.1 is broken.

**Comment by edoapra** [comment]
The fixed 5.8.1 tarball has been available since January 19th 2022 as
https://github.com/GlobalArrays/ga/releases/download/v5.8.1/ga-5.8.1.tar.gz

**Comment by yurivict** [comment]
So there is a discrepancy then between the GitHub release and the external tarball release.

**Comment by edoapra** [comment]
What files are you referring to?

The .tar.gz and .zip files were automatically generated before the bug was fixed.

Why would you want to use those files that have not gone through the same level of testing as the manually uploaded tarball? It seems an insane choice to me.

**Comment by yurivict** [comment]
I mean some distros may use github tags by default and they would use different source.
Tags are supposed to be in sync in GH and in tarballs.

**Comment by edoapra** [comment]
[Live fast, die young](https://en.wikipedia.org/wiki/Live_Fast_Die_Young)

**Pull request merged**
