### PR TITLE
remove Blue Gene/L and Blue Gene/P support

### PR DESCRIPTION
**Pull request by jeffhammond**
Support was removed in GA 5.4 (see changelog) but the code was not removed.  This commit removes the code.

I have not tested this yet.  It needs to be tested on a few different systems to make sure the control logic wasn't corrupted.

### CODE REVIEW

**Comment by jeffhammond** [comment]
@mblockso Are you going to miss this code? 😆

**Comment by mblockso** [comment]
Am I going to miss this code? Ahhhh .. no.

Curious that it has "BGML" functions.  That was a rename between BG/L and BG/P .. a very brief moment of time.

 - BGL originally had no (or no-name) message library because it only supported MPI.
 - Then an _amazing sales opportunity_ was identified if only we could run ARMCI on BG/L, so then we created "BGLML" from MPI guts
 - Then BG/P came around and it was considered silly to have "BGL" in the name, so then we had "BGML"
 - Then Roadrunner came around and it was considered equally silly to have "BG" in the name, so then we had "DCMF".
 - Then PERCS came around and it was considered silly to use an old name, so then we had "PAMI"
 
I hear PAMI eventually spawned UCX in some way.


Has anyone even tried GA with the OFI bgq provider? Just curious.

@charlesarcher

**Comment by jeffhammond** [comment]
I recall @pkcoff was looking at GA@OFI on BGQ.

**Comment by isubsmith** [comment]
PAMI is still in use actually. We see PAMI bugs on Summit :)

**Comment by charlesarcher** [comment]
@mblockso @isubsmith I’d be really impressed if you brought up pooled node storage, too:)

**Review by ajaypanyala — APPROVED** [review]

**Review by edoapra — APPROVED** [review]
It's not a good idea to push together cosmetic and real changes.

**Comment by jeffhammond** [comment]
Ok I'll try to fix it. I did this a long time ago but brought it back to life because Ajay is cleaning things up too.

**Pull request merged**
