### PR TITLE
Cmake subbuild

### PR DESCRIPTION
**Pull request by pjknowles**
I made a few changes to the cmake configuration in order to support (a) building ga as a subproject (b) building without fortran, as well as fixing the build for ntestc and ntestfc. More work could be done on robustly exporting the library, but for now this is enough for my needs.

### CODE REVIEW

**Comment by jeffhammond** [comment]
I don't use CMake with GA so hopefully Bruce can review this...

**Comment by bjpalmer** [comment]
My CMake was never that great to begin with and it is getting rustier over time, so hopefully I can give this a competent review. The CMAKE_SOURCE_DIR variable has been replaced by CMAKE_CURRENT_SOURCE_DIR in a number of places. If I understand the definitions of these variables correctly, this will break builds that are done in separate directories below the top level source directory, since the relative paths to different cmake directories will be incorrect. Do you want the .in files to be in the CMAKE_SOURCE_DIR and the .h files to end up in CMAKE_CURRENT_SOURCE_DIR?

Actually, looking at the original code, it is entirely possible that builds outside the top level source directory never worked.

**Comment by pjknowles** [comment]
Thanks Bruce. Let me try and explain in more detail what I did and why.

fb9f47c changes CMAKE_SOURCE_DIR to CMAKE_CURRENT_SOURCE_DIR only in the top level CMakeLists.txt . For regular building of ga, this has no effect whatsoever, since the two variables will have identical contents. For another project including ga, CMAKE_SOURCE_DIR is simply wrong and can not be what was intended - it is the top-level directory of that super-project. CMAKE_CURRENT_SOURCE_DIR is what is needed - it will always be the top-level directory of ga.

d875d54 is simply a bug-fix - you shouldn't try to test fortran code if its building has been disabled.

8cb747c is a bug fix - the source files for ntestc and ntestfc were over-specified, and this led to duplicate symbols at link time.

c270f09 is an enhancement to support use of the ga library by cmake super-projects, and essentially binds up all necessary include directories into the cmake notion of the library, so that is managed at the level of ga (correct) and not the super-project having knowledge of exactly which directories in the ga tree are needed (incorrect).  I do not know if I guessed exactly the right set of externally-accessible ga components. It does not affect regular building of the library. For the reasons for this, as well as why it is good practice to define an alias like ga::ga, look at, e.g., https://www.youtube.com/watch?v=bsXLMQ6WgIk . More could be done if you really wanted to wrap this up as a self-defining cmake-friendly library, but these first steps that I took are sufficient for my purpose, which is to drag ga automatically into the build of Molpro, via https://bitbucket.org/pjknowles/ppidd/src/cmake/src/CMakeLists.txt

Other than all that, my observation was that the cmake support in ga is thoughtfully done, and I was happy and grateful to discover it.

I would really appreciate it if you could consider these changes for official adoption, as it would save us having to maintain them for ever.

**Comment by pjknowles** [comment]
If there are any concerns about the safety of any of my changes, please feel free to discuss!

**Comment by bjpalmer** [comment]
I've tested these changes on our local Linux cluster. I needed to fix a bug related to building with the Fortran interface that has likely been present for some time but otherwise, the build seems to work as before. I've merged these changes into the develop branch.

**Pull request merged**
