### PR TITLE
rebased thread safe

### PR DESCRIPTION
**Pull request by jeffhammond**
With help from Pavan, I figured out how to rebase everything against develop after aligning the histories.

Please review and test this very carefully.  The changes are substantial.

Note that I deleted any build system code that caused a conflict, and it is possible that some of that will need to be restored if it was actually necessary.

### CODE REVIEW

**Comment by jeffhammond** [comment]
Note also that some work is unfinished.  I identified but have not fixed all of the races.  One easy fix is to protect unsafe accesses with a mutex.  This is true in e.g. the GA Fence code.

**Comment by jeffdaily** [comment]
I have looked through I think all of the commits.  After you made these changes, did you experience/test a thread-safe GA?  Do these changes assume a thread-safe ARMCI/ComEx?

**Comment by jeffhammond** [comment]
I think I tested GA but it has been a while so I don't remember the details.

First, these changes assume thread-safe ARMCI/ComEx.  Second, I do not claim that I have made GA completely thread-safe.  I merely claim it is much less thread-unsafe than it was before 😄

**Comment by jeffhammond** [comment]
These changes are being made in smaller pieces...

**Pull request closed without merging**
