### PR TITLE
test all MPI conduits, OFI and ARMCI-MPI

### PR DESCRIPTION
**Pull request by jeffdaily**

### CODE REVIEW

**Comment by jeffhammond** [comment]
Cool.  Most of the Travis builds are failing so it seems that I need to do some more debugging.

**Comment by jeffdaily** [comment]
Did you mean to use pipe `|` instead of the OR operator `||` for the various brew commands?

**Comment by jeffhammond** [comment]
@jeffdaily The intent was OR, because `install` fails if the package already exists, in which case it should just be `upgrade`d.

**Comment by jeffhammond** [comment]
It is amusing that I have made this error so many times and never been penalized 😮

**Pull request closed without merging**
