### PR TITLE
GA: use logical-and

### PR DESCRIPTION
**Pull request by jeffhammond**
Second step to resolve https://github.com/GlobalArrays/ga/issues/52.  This depends on https://github.com/GlobalArrays/ga/pull/62.

### CODE REVIEW

**Comment by jeffdaily** [comment]
Am I misreading something or does this really not depend on #62 as you claim?  I looked at both pull requests.  This one appears to be all of #62 + the use of the new operators.

**Comment by jeffhammond** [comment]
You read correctly.  This includes all of #62.  It would have been more correct to say that it inherits from #62.

**Comment by jeffhammond** [comment]
I removed all the K&R garbage from `armci/tcgmsg/ipcv4.0/globalop.c` and `armci/tcgmsg/ipcv5.0/globalop.c`.

**Comment by jeffdaily** [comment]
As soon as the checks pass (and they will) I'll pull this into develop.  It seemed too new to be considered for a hotifx to the 5.6 release.

**Pull request merged**
