### PR TITLE
Add sparse array operations to main development branch

### PR DESCRIPTION
**Pull request by bjpalmer**
Support for sparse distributed 2D arrays has been added to the repository. This includes support for setting up and distributing arrays and basic operations such as matrix-vector and matrix-matrix multiplies.

### CODE REVIEW

**Comment by edoapra** [comment]
@bjpalmer Did you rebase this branch correctly? There is a huge number of changes here ... are they all needed?

**Comment by edoapra** [comment]
some failure in the github action tests
```
/usr/bin/ld: ../libga.a(capi.c.o): in function `NGA_Sprs_array_create':
capi.c:(.text+0x16d37): undefined reference to `pnga_sprs_array_create'
```

**Comment by bjpalmer** [comment]
This is a fairly big chunk of  new functionality, so I'm not surprised that there are a lot of changes. Almost all of the changes are additions to the code. I'll check up on the CI fails.

**Comment by edoapra** [comment]
global/testing/gs_ran.x fails (it is not in the github action tests, though) with the error
```
Initial vector a_1

 global array: [1:8],  handle: -990 
   1       0.97563
   2       0.35161
   3      -0.42865
   4      -0.31672
   5       0.93024
   6       0.34336
   7      -0.36423
   8      -0.34972
0:length of V must equal second dimension of sparse matrix:Received an Error in Communication
```

**Comment by bjpalmer** [comment]
I'm working on corrections. The gs_ran.c code does not work and I'm taking it out of the test suite.

**Comment by bjpalmer** [comment]
I can make them smaller. I already did it for sprs_test.x and I'll look at the others.

**Review by ajaypanyala — APPROVED** [review]

**Pull request merged**
