### PR TITLE
remove deprecated code and build system logic

### PR DESCRIPTION
**Pull request by jeffhammond**
This commit removes a large amount of dead code that was declared deprecated in past releases.  Not carrying around obsolete, unmaintained baggage will make GA easier to maintain.  These changes have made the code - especially ARMCI - a lot more readable.

The deprecated platforms/interfaces include:
- IBM BGML (Blue Gene/L)
- IBM DCMF (Blue Gene/P)
- IBM LAPI
- VIA (we will have OpenIB and Mellanox targets for InfiniBand)
- GM (the older Myrinet API)
- Cray T3D, T3E, X1E (except instances in ghosts.c: https://github.com/GlobalArrays/ga/blob/1537981033d7b2e5cbeeaaf40529fbf4d414724a/global/src/ghosts.c#L3502, https://github.com/GlobalArrays/ga/blob/1537981033d7b2e5cbeeaaf40529fbf4d414724a/global/src/ghosts.c#L4325)
- Cray XT and SHMEM (I tried Cray SHMEM port but it doesn't appear to work on Cray XC systems)
- Cray Portals3 (went with the Cray XT systems)
- legacy (pre-XT) Cray systems
- PVM messaging library
- Fujitsu (back when they had some overlap with Cray SMPs)
- NEC (while NEC SX line still exists, no one has access or can test or support this platform)
- legacy SGI systems (when they had their own OS and used MIPS)
- Itanium
- SPARC
- DEC and DECOSF
- HPUX
- Ancient platforms (in TCGMSG): ALLIANT, ARDENT, DELTA, IPSC, CONVEX, APOLLO
- CCA (Common Component Architecture, which has been dead for over a decade)

It is likely that MPI-based conduits are equal or better than GM, VIA, LAPI, etc.  If a non-MPI port is desired, the OFI ComEx port is almost certainly a better starting point than ancient ARMCI code.

### CODE REVIEW

**Comment by jeffhammond** [comment]
I can test on IB.  I'll let you know the results.  I think I tested it already but not heavily.

**Comment by bjpalmer** [comment]
I tried running the check-ga test suite using the pull request build with openib and sockets. I'm getting a relatively large number of failures compared to the develop branch (the tests currently all pass in develop). I'll try doing some more checking to see if I can narrow down a point at which the test suite starts failing.

**Comment by jeffhammond** [comment]
What tests are failing?  I am having lots of trouble with `make check` but running tests by hand is fine.  I am running on a very heterogeneous machine where `MPIEXEC` isn't working and GA's `make check` doesn't give me a way to debug it.

**Comment by bjpalmer** [comment]
This is what I get running with openib and intel/intelmpi. The code eventually hangs on the simple_groups_commc.x test.

PASS: ma/test-coalesce.x
PASS: ma/test-inquire.x
XFAIL: ma/testf.x
PASS: global/testing/elempatch.x
PASS: global/testing/getmem.x
PASS: global/testing/mtest.x
PASS: global/testing/mulmatpatchc.x
PASS: global/testing/normc.x
PASS: global/testing/matrixc.x
PASS: global/testing/ntestc.x
PASS: global/testing/ntestfc.x
FAIL: global/testing/packc.x
PASS: global/testing/patch_enumc.x
PASS: global/testing/print.x
FAIL: global/testing/scan_addc.x
FAIL: global/testing/scan_copyc.x
PASS: global/testing/testc.x
PASS: global/testing/testmatmultc.x
PASS: global/testing/testmult.x
PASS: global/testing/testmultrect.x
PASS: global/testing/gemmtest.x
PASS: global/testing/read_only.x
FAIL: global/testing/unpackc.x
FAIL: global/testing/bin.x
FAIL: global/testing/blktest.x
PASS: global/testing/g2test.x
PASS: global/testing/g3test.x
FAIL: global/testing/ga_lu.x
PASS: global/testing/ga_shift.x
PASS: global/testing/ghosts.x
PASS: global/testing/jacobi.x
PASS: global/testing/mir_perf2.x
FAIL: global/testing/mmatrix.x
FAIL: global/testing/mulmatpatch.x
PASS: global/testing/nbtest.x
PASS: global/testing/nb2test.x
FAIL: global/testing/ndim.x
FAIL: global/testing/patch.x
PASS: global/testing/patch2.x
PASS: global/testing/patch_enumf.x
PASS: global/testing/perfmod.x
PASS: global/testing/perform.x
PASS: global/testing/perf.x
PASS: global/testing/perf2.x
FAIL: global/testing/pg2test.x
FAIL: global/testing/scan.x
PASS: global/testing/simple_groups.x
PASS: global/testing/sparse.x
FAIL: global/testing/sprsmatmult.x
PASS: global/testing/stride.x
FAIL: global/testing/testeig.x
PASS: global/testing/testmatmult.x
FAIL: global/testing/testsolve.x
FAIL: global/testing/test.x
PASS: global/testing/simple_groups_comm.x
FAIL: global/testing/ga-mpi.x
FAIL: global/testing/lock.x

**Comment by jeffhammond** [comment]
So far this is the only failure I see with sockets:
```
[jrhammon@pcl-tiergarten build-sockets]$ mpirun -H pcl-skx32,pcl-skx33 -n 1 gdb ./global/testing/testsolve.x 
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-110.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /nfs_home/jrhammon/GA/github/build-sockets/global/testing/testsolve.x...(no debugging symbols found)...done.
(gdb) run
Starting program: /nfs_home/jrhammon/GA/github/build-sockets/./global/testing/testsolve.x 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib64/libthread_db.so.1".
[New Thread 0x2aaaaf371700 (LWP 143327)]
[New Thread 0x2aaaafa08700 (LWP 143328)]
  filling in A and B  
  
 >Test of the LU-based solver with nxn rhs 
  

Program received signal SIGSEGV, Segmentation fault.
0x00000000004fe527 in gal_idamax_ ()
Missing separate debuginfos, use: debuginfo-install blas-3.4.2-8.el7.x86_64 bzip2-libs-1.0.6-13.el7.x86_64 elfutils-libelf-0.170-4.el7.x86_64 elfutils-libs-0.170-4.el7.x86_64 glibc-2.17-222.el7.x86_64 libattr-2.4.46-13.el7.x86_64 libcap-2.22-9.el7.x86_64 libgfortran-4.8.5-28.el7.x86_64 libpciaccess-0.14-1.el7.x86_64 libpsm2-11.2.7-1.x86_64 numactl-libs-2.0.9-7.el7.x86_64 systemd-libs-219-57.el7.x86_64 xz-libs-5.2.2-1.el7.x86_64 zlib-1.2.7-17.el7.x86_64
(gdb) bt
#0  0x00000000004fe527 in gal_idamax_ ()
#1  0x00000000004f1863 in gal_dgetf2_ ()
#2  0x00000000004d0288 in gal_dgetrf_ ()
#3  0x000000000042d970 in wnga_lu_solve_seq ()
#4  0x00000000004a78ca in wnga_lu_solve ()
#5  0x000000000042c3b1 in ga_lu_solve_ ()
#6  0x0000000000403dd0 in testit_ ()
#7  0x00000000004045f1 in MAIN__ ()
#8  0x00000000004046b2 in main ()
```

**Review by edoapra — DISMISSED** [review]

**Comment by jeffhammond** [comment]
@ajaypanyala i can't really tell at this point how much of this is in `develop` now but it looks like most of it, so i'm going to close this PR.  thanks for your help.

**Comment by ajaypanyala** [comment]
I would say almost all of it is in `develop`. Anything missing in develop should be minor at this point. Thanks for initiating this effort. This PR was a very good reference for the recent cleanup.

**Pull request closed without merging**
