### PR TITLE
Fix ctest of C programs

### PR DESCRIPTION
**Pull request by e-kwsm**
1. Add missing include guard and remove duplicated `print_subscript`
2. Fix signature of `main`
3. Fix paths to test executables and change `PASS_REGULAR_EXPRESSION` to "All tests successful"
4. Add missing "All tests successful"

### CODE REVIEW

**Comment by e-kwsm** [comment]
https://github.com/GlobalArrays/ga/blob/258546972deca14bf541be8b69d8becfdeed39ff/cmake-modules/GlobalArrays.cmake#L29-L34

I agree that this depends on machine, compilers, but isn't the value too short?
In my environment (MPICH 3.3.2/GCC 8.3.0) `testmatmultc_parallel` takes 86.66 sec.

**Comment by e-kwsm** [comment]
`mulmatpatchc_parallel` fails (#173).

**Review by edoapra — CHANGES_REQUESTED** [review]
These changes don't compile cleanly.
See Travis CI log in
https://travis-ci.org/github/GlobalArrays/ga/jobs/738213405
Please submit a PR against the `develop` branch

**Comment by e-kwsm** [comment]
7503fdb99d9695aa24123de3b63e08b44ff425d2 partly address #16.

20e918c1d8f3ea028d03672f942461734914b5d8 is unnecessary for test.

**Comment by ajaypanyala** [comment]
> https://github.com/GlobalArrays/ga/blob/258546972deca14bf541be8b69d8becfdeed39ff/cmake-modules/GlobalArrays.cmake#L29-L34
> 
> I agree that this depends on machine, compilers, but isn't the value too short?
> In my environment (MPICH 3.3.2/GCC 8.3.0) `testmatmultc_parallel` takes 86.66 sec.

@e-kwsm Are you working with the latest commit on the `develop` branch? The `cmake-modules` folder has been removed about 2 weeks ago, so not sure why you are seeing that. Could you please verify on your end?

**Comment by ajaypanyala** [comment]
Sorry, please ignore my previous comment. I noticed that you switch from `master` to `develop` after that.

**Pull request merged**
